name: linwini
description: App de recomendación de recetas según padecimientos e IMC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase - autenticación y base de datos
  supabase_flutter: ^2.5.6

  # HTTP - llamadas a Spoonacular API
  http: ^1.2.1

  # Manejo de variables de entorno
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo_ratatui.png